/* Generated at 2010/07/19 23:53:22; edit at your own risk. */

package amstin.models.meta;

import java.util.ArrayList;

@SuppressWarnings("unchecked")
public class Boot {
public static final amstin.models.meta.MetaModel instance;
static {
amstin.models.meta.Class obj6 = new amstin.models.meta.Class();
amstin.models.meta.Field obj18 = new amstin.models.meta.Field();
amstin.models.meta.Parent obj5 = new amstin.models.meta.Parent();
amstin.models.meta.Single obj40 = new amstin.models.meta.Single();
amstin.models.meta.None obj55 = new amstin.models.meta.None();
amstin.models.meta.Parent obj67 = new amstin.models.meta.Parent();
amstin.models.meta.Parent obj69 = new amstin.models.meta.Parent();
amstin.models.meta.None obj17 = new amstin.models.meta.None();
amstin.models.meta.Field obj25 = new amstin.models.meta.Field();
amstin.models.meta.Class obj4 = new amstin.models.meta.Class();
amstin.models.meta.Star obj52 = new amstin.models.meta.Star();
amstin.models.meta.Klass obj76 = new amstin.models.meta.Klass();
amstin.models.meta.Single obj27 = new amstin.models.meta.Single();
amstin.models.meta.Field obj34 = new amstin.models.meta.Field();
amstin.models.meta.Opt obj29 = new amstin.models.meta.Opt();
amstin.models.meta.Str obj15 = new amstin.models.meta.Str();
amstin.models.meta.Class obj58 = new amstin.models.meta.Class();
amstin.models.meta.Klass obj48 = new amstin.models.meta.Klass();
amstin.models.meta.Parent obj65 = new amstin.models.meta.Parent();
amstin.models.meta.MetaModel obj0 = new amstin.models.meta.MetaModel();
amstin.models.meta.Field obj31 = new amstin.models.meta.Field();
amstin.models.meta.None obj63 = new amstin.models.meta.None();
amstin.models.meta.Field obj38 = new amstin.models.meta.Field();
amstin.models.meta.Star obj77 = new amstin.models.meta.Star();
amstin.models.meta.Klass obj39 = new amstin.models.meta.Klass();
amstin.models.meta.Single obj16 = new amstin.models.meta.Single();
amstin.models.meta.Parent obj9 = new amstin.models.meta.Parent();
amstin.models.meta.Single obj20 = new amstin.models.meta.Single();
amstin.models.meta.None obj30 = new amstin.models.meta.None();
amstin.models.meta.Single obj73 = new amstin.models.meta.Single();
amstin.models.meta.Klass obj23 = new amstin.models.meta.Klass();
amstin.models.meta.Klass obj61 = new amstin.models.meta.Klass();
amstin.models.meta.Class obj8 = new amstin.models.meta.Class();
amstin.models.meta.Class obj49 = new amstin.models.meta.Class();
amstin.models.meta.Klass obj32 = new amstin.models.meta.Klass();
amstin.models.meta.Class obj12 = new amstin.models.meta.Class();
amstin.models.meta.Str obj35 = new amstin.models.meta.Str();
amstin.models.meta.None obj53 = new amstin.models.meta.None();
amstin.models.meta.None obj46 = new amstin.models.meta.None();
amstin.models.meta.None obj37 = new amstin.models.meta.None();
amstin.models.meta.Field obj14 = new amstin.models.meta.Field();
amstin.models.meta.Field obj71 = new amstin.models.meta.Field();
amstin.models.meta.None obj51 = new amstin.models.meta.None();
amstin.models.meta.Class obj33 = new amstin.models.meta.Class();
amstin.models.meta.Class obj70 = new amstin.models.meta.Class();
amstin.models.meta.Klass obj26 = new amstin.models.meta.Klass();
amstin.models.meta.Parent obj57 = new amstin.models.meta.Parent();
amstin.models.meta.None obj78 = new amstin.models.meta.None();
amstin.models.meta.None obj21 = new amstin.models.meta.None();
amstin.models.meta.Klass obj43 = new amstin.models.meta.Klass();
amstin.models.meta.Parent obj3 = new amstin.models.meta.Parent();
amstin.models.meta.Field obj47 = new amstin.models.meta.Field();
amstin.models.meta.Parent obj13 = new amstin.models.meta.Parent();
amstin.models.meta.Class obj64 = new amstin.models.meta.Class();
amstin.models.meta.Class obj66 = new amstin.models.meta.Class();
amstin.models.meta.Class obj24 = new amstin.models.meta.Class();
amstin.models.meta.Class obj44 = new amstin.models.meta.Class();
amstin.models.meta.Single obj45 = new amstin.models.meta.Single();
amstin.models.meta.Bool obj19 = new amstin.models.meta.Bool();
amstin.models.meta.Field obj60 = new amstin.models.meta.Field();
amstin.models.meta.Class obj68 = new amstin.models.meta.Class();
amstin.models.meta.Field obj75 = new amstin.models.meta.Field();
amstin.models.meta.Field obj42 = new amstin.models.meta.Field();
amstin.models.meta.Klass obj11 = new amstin.models.meta.Klass();
amstin.models.meta.Opt obj50 = new amstin.models.meta.Opt();
amstin.models.meta.Field obj22 = new amstin.models.meta.Field();
amstin.models.meta.Class obj2 = new amstin.models.meta.Class();
amstin.models.meta.Class obj1 = new amstin.models.meta.Class();
amstin.models.meta.Single obj62 = new amstin.models.meta.Single();
amstin.models.meta.Single obj54 = new amstin.models.meta.Single();
amstin.models.meta.Class obj56 = new amstin.models.meta.Class();
amstin.models.meta.None obj74 = new amstin.models.meta.None();
amstin.models.meta.Parent obj7 = new amstin.models.meta.Parent();
amstin.models.meta.None obj28 = new amstin.models.meta.None();
amstin.models.meta.Parent obj59 = new amstin.models.meta.Parent();
amstin.models.meta.Str obj72 = new amstin.models.meta.Str();
amstin.models.meta.None obj41 = new amstin.models.meta.None();
amstin.models.meta.Field obj10 = new amstin.models.meta.Field();
amstin.models.meta.Single obj36 = new amstin.models.meta.Single();
obj6.name = "Bool";
obj6.isAbstract = false;
obj6.parent = obj7;
obj6.fields = new ArrayList();
obj18.name = "isAbstract";
obj18.type = obj19;
obj18.mult = obj20;
obj18.inverse = obj21;
obj18.owner = null;
obj5.type = obj1;
obj67.type = obj44;
obj69.type = obj44;
obj25.name = "type";
obj25.type = obj26;
obj25.mult = obj27;
obj25.inverse = obj28;
obj25.owner = null;
obj4.name = "Str";
obj4.isAbstract = false;
obj4.parent = obj5;
obj4.fields = new ArrayList();
obj76.klass = obj12;
obj34.name = "name";
obj34.type = obj35;
obj34.mult = obj36;
obj34.inverse = obj37;
obj34.owner = null;
obj58.name = "Other";
obj58.isAbstract = false;
obj58.parent = obj59;
obj58.fields = new ArrayList<amstin.models.meta.Field>();
obj58.fields.add(obj60);
obj48.klass = obj49;
obj65.type = obj44;
obj0.classes = new ArrayList<amstin.models.meta.Class>();
obj0.classes.add(obj1);
obj0.classes.add(obj2);
obj0.classes.add(obj4);
obj0.classes.add(obj6);
obj0.classes.add(obj8);
obj0.classes.add(obj12);
obj0.classes.add(obj24);
obj0.classes.add(obj33);
obj0.classes.add(obj49);
obj0.classes.add(obj56);
obj0.classes.add(obj58);
obj0.classes.add(obj44);
obj0.classes.add(obj64);
obj0.classes.add(obj66);
obj0.classes.add(obj68);
obj0.classes.add(obj70);
obj0.name = "MetaMetaModel";
obj31.name = "fields";
obj31.type = obj32;
obj31.mult = obj52;
obj31.inverse = obj53;
obj31.owner = null;
obj38.name = "type";
obj38.type = obj39;
obj38.mult = obj40;
obj38.inverse = obj41;
obj38.owner = null;
obj39.klass = obj1;
obj9.type = obj1;
obj23.klass = obj24;
obj61.klass = obj33;
obj8.name = "Klass";
obj8.isAbstract = false;
obj8.parent = obj9;
obj8.fields = new ArrayList<amstin.models.meta.Field>();
obj8.fields.add(obj10);
obj49.name = "Inverse";
obj49.isAbstract = true;
obj49.parent = null;
obj49.fields = new ArrayList();
obj32.klass = obj33;
obj12.name = "Class";
obj12.isAbstract = false;
obj12.parent = obj13;
obj12.fields = new ArrayList<amstin.models.meta.Field>();
obj12.fields.add(obj14);
obj12.fields.add(obj18);
obj12.fields.add(obj22);
obj12.fields.add(obj31);
obj14.name = "name";
obj14.type = obj15;
obj14.mult = obj16;
obj14.inverse = obj17;
obj14.owner = null;
obj71.name = "name";
obj71.type = obj72;
obj71.mult = obj73;
obj71.inverse = obj74;
obj71.owner = null;
obj33.name = "Field";
obj33.isAbstract = false;
obj33.parent = null;
obj33.fields = new ArrayList<amstin.models.meta.Field>();
obj33.fields.add(obj34);
obj33.fields.add(obj38);
obj33.fields.add(obj42);
obj33.fields.add(obj47);
obj70.name = "MetaModel";
obj70.isAbstract = false;
obj70.parent = null;
obj70.fields = new ArrayList<amstin.models.meta.Field>();
obj70.fields.add(obj71);
obj70.fields.add(obj75);
obj26.klass = obj12;
obj57.type = obj49;
obj43.klass = obj44;
obj3.type = obj1;
obj47.name = "inverse";
obj47.type = obj48;
obj47.mult = obj50;
obj47.inverse = obj51;
obj47.owner = null;
obj13.type = obj1;
obj64.name = "Single";
obj64.isAbstract = false;
obj64.parent = obj65;
obj64.fields = new ArrayList();
obj66.name = "Star";
obj66.isAbstract = false;
obj66.parent = obj67;
obj66.fields = new ArrayList();
obj24.name = "Parent";
obj24.isAbstract = false;
obj24.parent = null;
obj24.fields = new ArrayList<amstin.models.meta.Field>();
obj24.fields.add(obj25);
obj44.name = "Mult";
obj44.isAbstract = true;
obj44.parent = null;
obj44.fields = new ArrayList();
obj60.name = "other";
obj60.type = obj61;
obj60.mult = obj62;
obj60.inverse = obj63;
obj60.owner = null;
obj68.name = "Opt";
obj68.isAbstract = false;
obj68.parent = obj69;
obj68.fields = new ArrayList();
obj75.name = "classes";
obj75.type = obj76;
obj75.mult = obj77;
obj75.inverse = obj78;
obj75.owner = null;
obj42.name = "mult";
obj42.type = obj43;
obj42.mult = obj45;
obj42.inverse = obj46;
obj42.owner = null;
obj11.klass = obj12;
obj22.name = "parent";
obj22.type = obj23;
obj22.mult = obj29;
obj22.inverse = obj30;
obj22.owner = null;
obj2.name = "Int";
obj2.isAbstract = false;
obj2.parent = obj3;
obj2.fields = new ArrayList();
obj1.name = "Type";
obj1.isAbstract = true;
obj1.parent = null;
obj1.fields = new ArrayList();
obj56.name = "None";
obj56.isAbstract = false;
obj56.parent = obj57;
obj56.fields = new ArrayList();
obj7.type = obj1;
obj59.type = obj49;
obj10.name = "klass";
obj10.type = obj11;
obj10.mult = obj54;
obj10.inverse = obj55;
obj10.owner = null;
instance = obj0;
}
}
