/* Generated at 2010/08/03 16:39:57; edit at your own risk. */

package amstin.models.meta;

import java.util.ArrayList;

@SuppressWarnings("unchecked")
public class Boot {
public static final amstin.models.meta.MetaModel instance;
static {
amstin.models.meta.Single obj29 = new amstin.models.meta.Single();
amstin.models.meta.MetaModel obj0 = new amstin.models.meta.MetaModel();
amstin.models.meta.Single obj42 = new amstin.models.meta.Single();
amstin.models.meta.Single obj47 = new amstin.models.meta.Single();
amstin.models.meta.Klass obj63 = new amstin.models.meta.Klass();
amstin.models.meta.Single obj38 = new amstin.models.meta.Single();
amstin.models.meta.Single obj18 = new amstin.models.meta.Single();
amstin.models.meta.Single obj22 = new amstin.models.meta.Single();
amstin.models.meta.Star obj54 = new amstin.models.meta.Star();
amstin.models.meta.Parent obj7 = new amstin.models.meta.Parent();
amstin.models.meta.Class obj68 = new amstin.models.meta.Class();
amstin.models.meta.Class obj10 = new amstin.models.meta.Class();
amstin.models.meta.Klass obj13 = new amstin.models.meta.Klass();
amstin.models.meta.Parent obj15 = new amstin.models.meta.Parent();
amstin.models.meta.Class obj72 = new amstin.models.meta.Class();
amstin.models.meta.Field obj49 = new amstin.models.meta.Field();
amstin.models.meta.Single obj56 = new amstin.models.meta.Single();
amstin.models.meta.Str obj74 = new amstin.models.meta.Str();
amstin.models.meta.Parent obj11 = new amstin.models.meta.Parent();
amstin.models.meta.Class obj4 = new amstin.models.meta.Class();
amstin.models.meta.Field obj44 = new amstin.models.meta.Field();
amstin.models.meta.Parent obj59 = new amstin.models.meta.Parent();
amstin.models.meta.Parent obj69 = new amstin.models.meta.Parent();
amstin.models.meta.Parent obj71 = new amstin.models.meta.Parent();
amstin.models.meta.None obj55 = new amstin.models.meta.None();
amstin.models.meta.Opt obj52 = new amstin.models.meta.Opt();
amstin.models.meta.Field obj36 = new amstin.models.meta.Field();
amstin.models.meta.Class obj8 = new amstin.models.meta.Class();
amstin.models.meta.Class obj2 = new amstin.models.meta.Class();
amstin.models.meta.Bool obj21 = new amstin.models.meta.Bool();
amstin.models.meta.Parent obj67 = new amstin.models.meta.Parent();
amstin.models.meta.Single obj75 = new amstin.models.meta.Single();
amstin.models.meta.Class obj46 = new amstin.models.meta.Class();
amstin.models.meta.Class obj66 = new amstin.models.meta.Class();
amstin.models.meta.Klass obj45 = new amstin.models.meta.Klass();
amstin.models.meta.Class obj51 = new amstin.models.meta.Class();
amstin.models.meta.Klass obj34 = new amstin.models.meta.Klass();
amstin.models.meta.Field obj77 = new amstin.models.meta.Field();
amstin.models.meta.None obj65 = new amstin.models.meta.None();
amstin.models.meta.Parent obj9 = new amstin.models.meta.Parent();
amstin.models.meta.Field obj33 = new amstin.models.meta.Field();
amstin.models.meta.Class obj6 = new amstin.models.meta.Class();
amstin.models.meta.Field obj12 = new amstin.models.meta.Field();
amstin.models.meta.None obj23 = new amstin.models.meta.None();
amstin.models.meta.None obj39 = new amstin.models.meta.None();
amstin.models.meta.None obj57 = new amstin.models.meta.None();
amstin.models.meta.Klass obj50 = new amstin.models.meta.Klass();
amstin.models.meta.Class obj70 = new amstin.models.meta.Class();
amstin.models.meta.Star obj79 = new amstin.models.meta.Star();
amstin.models.meta.Parent obj3 = new amstin.models.meta.Parent();
amstin.models.meta.None obj30 = new amstin.models.meta.None();
amstin.models.meta.None obj19 = new amstin.models.meta.None();
amstin.models.meta.Klass obj41 = new amstin.models.meta.Klass();
amstin.models.meta.Class obj60 = new amstin.models.meta.Class();
amstin.models.meta.None obj48 = new amstin.models.meta.None();
amstin.models.meta.Class obj1 = new amstin.models.meta.Class();
amstin.models.meta.Field obj16 = new amstin.models.meta.Field();
amstin.models.meta.Str obj17 = new amstin.models.meta.Str();
amstin.models.meta.Field obj20 = new amstin.models.meta.Field();
amstin.models.meta.None obj32 = new amstin.models.meta.None();
amstin.models.meta.None obj53 = new amstin.models.meta.None();
amstin.models.meta.Klass obj25 = new amstin.models.meta.Klass();
amstin.models.meta.Field obj62 = new amstin.models.meta.Field();
amstin.models.meta.None obj76 = new amstin.models.meta.None();
amstin.models.meta.Parent obj5 = new amstin.models.meta.Parent();
amstin.models.meta.Class obj58 = new amstin.models.meta.Class();
amstin.models.meta.Str obj37 = new amstin.models.meta.Str();
amstin.models.meta.Single obj64 = new amstin.models.meta.Single();
amstin.models.meta.None obj80 = new amstin.models.meta.None();
amstin.models.meta.None obj43 = new amstin.models.meta.None();
amstin.models.meta.Klass obj78 = new amstin.models.meta.Klass();
amstin.models.meta.Field obj24 = new amstin.models.meta.Field();
amstin.models.meta.Class obj14 = new amstin.models.meta.Class();
amstin.models.meta.Field obj27 = new amstin.models.meta.Field();
amstin.models.meta.Class obj26 = new amstin.models.meta.Class();
amstin.models.meta.Klass obj28 = new amstin.models.meta.Klass();
amstin.models.meta.Parent obj61 = new amstin.models.meta.Parent();
amstin.models.meta.Opt obj31 = new amstin.models.meta.Opt();
amstin.models.meta.Field obj73 = new amstin.models.meta.Field();
amstin.models.meta.Field obj40 = new amstin.models.meta.Field();
amstin.models.meta.Class obj35 = new amstin.models.meta.Class();
obj0.classes = new ArrayList<amstin.models.meta.Class>();
obj0.classes.add(obj1);
obj0.classes.add(obj2);
obj0.classes.add(obj4);
obj0.classes.add(obj6);
obj0.classes.add(obj8);
obj0.classes.add(obj10);
obj0.classes.add(obj14);
obj0.classes.add(obj26);
obj0.classes.add(obj35);
obj0.classes.add(obj51);
obj0.classes.add(obj58);
obj0.classes.add(obj60);
obj0.classes.add(obj46);
obj0.classes.add(obj66);
obj0.classes.add(obj68);
obj0.classes.add(obj70);
obj0.classes.add(obj72);
obj0.name = "MetaMetaModel";
obj63.klass = obj35;
obj7.type = obj1;
obj68.name = "Star";
obj68.isAbstract = false;
obj68.parent = obj69;
obj68.fields = new ArrayList();
obj10.name = "Klass";
obj10.isAbstract = false;
obj10.parent = obj11;
obj10.fields = new ArrayList<amstin.models.meta.Field>();
obj10.fields.add(obj12);
obj13.klass = obj14;
obj15.type = obj1;
obj72.name = "MetaModel";
obj72.isAbstract = false;
obj72.parent = null;
obj72.fields = new ArrayList<amstin.models.meta.Field>();
obj72.fields.add(obj73);
obj72.fields.add(obj77);
obj49.name = "inverse";
obj49.type = obj50;
obj49.mult = obj52;
obj49.inverse = obj53;
obj49.owner = null;
obj11.type = obj1;
obj4.name = "Str";
obj4.isAbstract = false;
obj4.parent = obj5;
obj4.fields = new ArrayList();
obj44.name = "mult";
obj44.type = obj45;
obj44.mult = obj47;
obj44.inverse = obj48;
obj44.owner = null;
obj59.type = obj51;
obj69.type = obj46;
obj71.type = obj46;
obj36.name = "name";
obj36.type = obj37;
obj36.mult = obj38;
obj36.inverse = obj39;
obj36.owner = null;
obj8.name = "Real";
obj8.isAbstract = false;
obj8.parent = obj9;
obj8.fields = new ArrayList();
obj2.name = "Int";
obj2.isAbstract = false;
obj2.parent = obj3;
obj2.fields = new ArrayList();
obj67.type = obj46;
obj46.name = "Mult";
obj46.isAbstract = true;
obj46.parent = null;
obj46.fields = new ArrayList();
obj66.name = "Single";
obj66.isAbstract = false;
obj66.parent = obj67;
obj66.fields = new ArrayList();
obj45.klass = obj46;
obj51.name = "Inverse";
obj51.isAbstract = true;
obj51.parent = null;
obj51.fields = new ArrayList();
obj34.klass = obj35;
obj77.name = "classes";
obj77.type = obj78;
obj77.mult = obj79;
obj77.inverse = obj80;
obj77.owner = null;
obj9.type = obj1;
obj33.name = "fields";
obj33.type = obj34;
obj33.mult = obj54;
obj33.inverse = obj55;
obj33.owner = null;
obj6.name = "Bool";
obj6.isAbstract = false;
obj6.parent = obj7;
obj6.fields = new ArrayList();
obj12.name = "klass";
obj12.type = obj13;
obj12.mult = obj56;
obj12.inverse = obj57;
obj12.owner = null;
obj50.klass = obj51;
obj70.name = "Opt";
obj70.isAbstract = false;
obj70.parent = obj71;
obj70.fields = new ArrayList();
obj3.type = obj1;
obj41.klass = obj1;
obj60.name = "Other";
obj60.isAbstract = false;
obj60.parent = obj61;
obj60.fields = new ArrayList<amstin.models.meta.Field>();
obj60.fields.add(obj62);
obj1.name = "Type";
obj1.isAbstract = true;
obj1.parent = null;
obj1.fields = new ArrayList();
obj16.name = "name";
obj16.type = obj17;
obj16.mult = obj18;
obj16.inverse = obj19;
obj16.owner = null;
obj20.name = "isAbstract";
obj20.type = obj21;
obj20.mult = obj22;
obj20.inverse = obj23;
obj20.owner = null;
obj25.klass = obj26;
obj62.name = "other";
obj62.type = obj63;
obj62.mult = obj64;
obj62.inverse = obj65;
obj62.owner = null;
obj5.type = obj1;
obj58.name = "None";
obj58.isAbstract = false;
obj58.parent = obj59;
obj58.fields = new ArrayList();
obj78.klass = obj14;
obj24.name = "parent";
obj24.type = obj25;
obj24.mult = obj31;
obj24.inverse = obj32;
obj24.owner = null;
obj14.name = "Class";
obj14.isAbstract = false;
obj14.parent = obj15;
obj14.fields = new ArrayList<amstin.models.meta.Field>();
obj14.fields.add(obj16);
obj14.fields.add(obj20);
obj14.fields.add(obj24);
obj14.fields.add(obj33);
obj27.name = "type";
obj27.type = obj28;
obj27.mult = obj29;
obj27.inverse = obj30;
obj27.owner = null;
obj26.name = "Parent";
obj26.isAbstract = false;
obj26.parent = null;
obj26.fields = new ArrayList<amstin.models.meta.Field>();
obj26.fields.add(obj27);
obj28.klass = obj14;
obj61.type = obj51;
obj73.name = "name";
obj73.type = obj74;
obj73.mult = obj75;
obj73.inverse = obj76;
obj73.owner = null;
obj40.name = "type";
obj40.type = obj41;
obj40.mult = obj42;
obj40.inverse = obj43;
obj40.owner = null;
obj35.name = "Field";
obj35.isAbstract = false;
obj35.parent = null;
obj35.fields = new ArrayList<amstin.models.meta.Field>();
obj35.fields.add(obj36);
obj35.fields.add(obj40);
obj35.fields.add(obj44);
obj35.fields.add(obj49);
instance = obj0;
}
}
