/* Generated at 2010/06/26 07:08:55; edit at your own risk. */

package amstin.models.meta;

import java.util.ArrayList;

@SuppressWarnings("unchecked")
public class Boot {
public static final amstin.models.meta.MetaModel instance;
static {
amstin.models.meta.Field obj51 = new amstin.models.meta.Field();
amstin.models.meta.Klass obj36 = new amstin.models.meta.Klass();
amstin.models.meta.Str obj52 = new amstin.models.meta.Str();
amstin.models.meta.Class obj24 = new amstin.models.meta.Class();
amstin.models.meta.Str obj17 = new amstin.models.meta.Str();
amstin.models.meta.Field obj19 = new amstin.models.meta.Field();
amstin.models.meta.Class obj46 = new amstin.models.meta.Class();
amstin.models.meta.Klass obj13 = new amstin.models.meta.Klass();
amstin.models.meta.Parent obj15 = new amstin.models.meta.Parent();
amstin.models.meta.Star obj42 = new amstin.models.meta.Star();
amstin.models.meta.Parent obj47 = new amstin.models.meta.Parent();
amstin.models.meta.Parent obj49 = new amstin.models.meta.Parent();
amstin.models.meta.Class obj6 = new amstin.models.meta.Class();
amstin.models.meta.Field obj38 = new amstin.models.meta.Field();
amstin.models.meta.Class obj31 = new amstin.models.meta.Class();
amstin.models.meta.Opt obj28 = new amstin.models.meta.Opt();
amstin.models.meta.Parent obj45 = new amstin.models.meta.Parent();
amstin.models.meta.Klass obj30 = new amstin.models.meta.Klass();
amstin.models.meta.Parent obj9 = new amstin.models.meta.Parent();
amstin.models.meta.Class obj4 = new amstin.models.meta.Class();
amstin.models.meta.Star obj56 = new amstin.models.meta.Star();
amstin.models.meta.Parent obj5 = new amstin.models.meta.Parent();
amstin.models.meta.Class obj40 = new amstin.models.meta.Class();
amstin.models.meta.Klass obj39 = new amstin.models.meta.Klass();
amstin.models.meta.Class obj44 = new amstin.models.meta.Class();
amstin.models.meta.Class obj50 = new amstin.models.meta.Class();
amstin.models.meta.Field obj54 = new amstin.models.meta.Field();
amstin.models.meta.Class obj10 = new amstin.models.meta.Class();
amstin.models.meta.Single obj27 = new amstin.models.meta.Single();
amstin.models.meta.Field obj12 = new amstin.models.meta.Field();
amstin.models.meta.Field obj32 = new amstin.models.meta.Field();
amstin.models.meta.Class obj8 = new amstin.models.meta.Class();
amstin.models.meta.Single obj43 = new amstin.models.meta.Single();
amstin.models.meta.Field obj25 = new amstin.models.meta.Field();
amstin.models.meta.Field obj35 = new amstin.models.meta.Field();
amstin.models.meta.Parent obj3 = new amstin.models.meta.Parent();
amstin.models.meta.Single obj41 = new amstin.models.meta.Single();
amstin.models.meta.Class obj2 = new amstin.models.meta.Class();
amstin.models.meta.Single obj18 = new amstin.models.meta.Single();
amstin.models.meta.Klass obj26 = new amstin.models.meta.Klass();
amstin.models.meta.Single obj21 = new amstin.models.meta.Single();
amstin.models.meta.Single obj34 = new amstin.models.meta.Single();
amstin.models.meta.Klass obj55 = new amstin.models.meta.Klass();
amstin.models.meta.Parent obj7 = new amstin.models.meta.Parent();
amstin.models.meta.Class obj48 = new amstin.models.meta.Class();
amstin.models.meta.Single obj53 = new amstin.models.meta.Single();
amstin.models.meta.Single obj37 = new amstin.models.meta.Single();
amstin.models.meta.Bool obj20 = new amstin.models.meta.Bool();
amstin.models.meta.Class obj14 = new amstin.models.meta.Class();
amstin.models.meta.Klass obj23 = new amstin.models.meta.Klass();
amstin.models.meta.Field obj16 = new amstin.models.meta.Field();
amstin.models.meta.Field obj22 = new amstin.models.meta.Field();
amstin.models.meta.Class obj1 = new amstin.models.meta.Class();
amstin.models.meta.Parent obj11 = new amstin.models.meta.Parent();
amstin.models.meta.MetaModel obj0 = new amstin.models.meta.MetaModel();
amstin.models.meta.Str obj33 = new amstin.models.meta.Str();
amstin.models.meta.Field obj29 = new amstin.models.meta.Field();
obj51.name = "name";
obj51.type = obj52;
obj51.mult = obj53;
obj36.klass = obj1;
obj24.name = "Parent";
obj24.isAbstract = false;
obj24.parent = null;
obj24.fields = new ArrayList<amstin.models.meta.Field>();
obj24.fields.add(obj25);
obj19.name = "isAbstract";
obj19.type = obj20;
obj19.mult = obj21;
obj46.name = "Star";
obj46.isAbstract = false;
obj46.parent = obj47;
obj46.fields = new ArrayList();
obj13.klass = obj14;
obj15.type = obj1;
obj47.type = obj40;
obj49.type = obj40;
obj6.name = "Bool";
obj6.isAbstract = false;
obj6.parent = obj7;
obj6.fields = new ArrayList();
obj38.name = "mult";
obj38.type = obj39;
obj38.mult = obj41;
obj31.name = "Field";
obj31.isAbstract = false;
obj31.parent = null;
obj31.fields = new ArrayList<amstin.models.meta.Field>();
obj31.fields.add(obj32);
obj31.fields.add(obj35);
obj31.fields.add(obj38);
obj45.type = obj40;
obj30.klass = obj31;
obj9.type = obj1;
obj4.name = "Str";
obj4.isAbstract = false;
obj4.parent = obj5;
obj4.fields = new ArrayList();
obj5.type = obj1;
obj40.name = "Mult";
obj40.isAbstract = true;
obj40.parent = null;
obj40.fields = new ArrayList();
obj39.klass = obj40;
obj44.name = "Single";
obj44.isAbstract = false;
obj44.parent = obj45;
obj44.fields = new ArrayList();
obj50.name = "MetaModel";
obj50.isAbstract = false;
obj50.parent = null;
obj50.fields = new ArrayList<amstin.models.meta.Field>();
obj50.fields.add(obj51);
obj50.fields.add(obj54);
obj54.name = "classes";
obj54.type = obj55;
obj54.mult = obj56;
obj10.name = "Klass";
obj10.isAbstract = false;
obj10.parent = obj11;
obj10.fields = new ArrayList<amstin.models.meta.Field>();
obj10.fields.add(obj12);
obj12.name = "klass";
obj12.type = obj13;
obj12.mult = obj43;
obj32.name = "name";
obj32.type = obj33;
obj32.mult = obj34;
obj8.name = "Id";
obj8.isAbstract = false;
obj8.parent = obj9;
obj8.fields = new ArrayList();
obj25.name = "type";
obj25.type = obj26;
obj25.mult = obj27;
obj35.name = "type";
obj35.type = obj36;
obj35.mult = obj37;
obj3.type = obj1;
obj2.name = "Int";
obj2.isAbstract = false;
obj2.parent = obj3;
obj2.fields = new ArrayList();
obj26.klass = obj14;
obj55.klass = obj14;
obj7.type = obj1;
obj48.name = "Opt";
obj48.isAbstract = false;
obj48.parent = obj49;
obj48.fields = new ArrayList();
obj14.name = "Class";
obj14.isAbstract = false;
obj14.parent = obj15;
obj14.fields = new ArrayList<amstin.models.meta.Field>();
obj14.fields.add(obj16);
obj14.fields.add(obj19);
obj14.fields.add(obj22);
obj14.fields.add(obj29);
obj23.klass = obj24;
obj16.name = "name";
obj16.type = obj17;
obj16.mult = obj18;
obj22.name = "parent";
obj22.type = obj23;
obj22.mult = obj28;
obj1.name = "Type";
obj1.isAbstract = true;
obj1.parent = null;
obj1.fields = new ArrayList();
obj11.type = obj1;
obj0.classes = new ArrayList<amstin.models.meta.Class>();
obj0.classes.add(obj1);
obj0.classes.add(obj2);
obj0.classes.add(obj4);
obj0.classes.add(obj6);
obj0.classes.add(obj8);
obj0.classes.add(obj10);
obj0.classes.add(obj14);
obj0.classes.add(obj24);
obj0.classes.add(obj31);
obj0.classes.add(obj40);
obj0.classes.add(obj44);
obj0.classes.add(obj46);
obj0.classes.add(obj48);
obj0.classes.add(obj50);
obj0.name = "MetaMetaModel";
obj29.name = "fields";
obj29.type = obj30;
obj29.mult = obj42;
instance = obj0;
}
}
