/* Generated at 2010/07/28 08:36:33; edit at your own risk. */

package amstin.models.grammar;

import java.util.ArrayList;

@SuppressWarnings("unchecked")
public class Boot {
public static final amstin.models.grammar.Grammar instance;
static {
amstin.models.grammar.Label obj62 = new amstin.models.grammar.Label();
amstin.models.grammar.Label obj39 = new amstin.models.grammar.Label();
amstin.models.grammar.Alt obj99 = new amstin.models.grammar.Alt();
amstin.models.grammar.Label obj9 = new amstin.models.grammar.Label();
amstin.models.grammar.Str obj87 = new amstin.models.grammar.Str();
amstin.models.grammar.Ref obj63 = new amstin.models.grammar.Ref();
amstin.models.grammar.Klass obj77 = new amstin.models.grammar.Klass();
amstin.models.grammar.Element obj38 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj50 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj97 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj55 = new amstin.models.grammar.Element();
amstin.models.grammar.Str obj122 = new amstin.models.grammar.Str();
amstin.models.grammar.Element obj129 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj86 = new amstin.models.grammar.Label();
amstin.models.grammar.Str obj136 = new amstin.models.grammar.Str();
amstin.models.grammar.Label obj56 = new amstin.models.grammar.Label();
amstin.models.grammar.Sym obj47 = new amstin.models.grammar.Sym();
amstin.models.grammar.Alt obj30 = new amstin.models.grammar.Alt();
amstin.models.grammar.Alt obj2 = new amstin.models.grammar.Alt();
amstin.models.grammar.Element obj19 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj37 = new amstin.models.grammar.Lit();
amstin.models.grammar.Rule obj1 = new amstin.models.grammar.Rule();
amstin.models.grammar.Element obj17 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj76 = new amstin.models.grammar.Alt();
amstin.models.grammar.Lit obj32 = new amstin.models.grammar.Lit();
amstin.models.grammar.Alt obj88 = new amstin.models.grammar.Alt();
amstin.models.grammar.Sym obj103 = new amstin.models.grammar.Sym();
amstin.models.grammar.Alt obj106 = new amstin.models.grammar.Alt();
amstin.models.grammar.Alt obj59 = new amstin.models.grammar.Alt();
amstin.models.grammar.Lit obj75 = new amstin.models.grammar.Lit();
amstin.models.grammar.Label obj79 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj108 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj115 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj118 = new amstin.models.grammar.Label();
amstin.models.grammar.Alt obj83 = new amstin.models.grammar.Alt();
amstin.models.grammar.Label obj132 = new amstin.models.grammar.Label();
amstin.models.grammar.Opt obj46 = new amstin.models.grammar.Opt();
amstin.models.grammar.Alt obj24 = new amstin.models.grammar.Alt();
amstin.models.grammar.Alt obj49 = new amstin.models.grammar.Alt();
amstin.models.grammar.Sym obj57 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj85 = new amstin.models.grammar.Element();
amstin.models.grammar.Klass obj114 = new amstin.models.grammar.Klass();
amstin.models.grammar.Element obj123 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj98 = new amstin.models.grammar.Lit();
amstin.models.grammar.Label obj15 = new amstin.models.grammar.Label();
amstin.models.grammar.Label obj26 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj44 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj54 = new amstin.models.grammar.Lit();
amstin.models.grammar.Lit obj138 = new amstin.models.grammar.Lit();
amstin.models.grammar.IterStar obj10 = new amstin.models.grammar.IterStar();
amstin.models.grammar.Key obj16 = new amstin.models.grammar.Key();
amstin.models.grammar.Element obj78 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj131 = new amstin.models.grammar.Element();
amstin.models.grammar.Klass obj73 = new amstin.models.grammar.Klass();
amstin.models.grammar.Element obj104 = new amstin.models.grammar.Element();
amstin.models.grammar.Klass obj107 = new amstin.models.grammar.Klass();
amstin.models.grammar.Id obj35 = new amstin.models.grammar.Id();
amstin.models.grammar.Rule obj23 = new amstin.models.grammar.Rule();
amstin.models.grammar.Alt obj43 = new amstin.models.grammar.Alt();
amstin.models.grammar.Label obj51 = new amstin.models.grammar.Label();
amstin.models.grammar.Lit obj124 = new amstin.models.grammar.Lit();
amstin.models.grammar.Lit obj126 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj74 = new amstin.models.grammar.Element();
amstin.models.grammar.Sym obj133 = new amstin.models.grammar.Sym();
amstin.models.grammar.Klass obj69 = new amstin.models.grammar.Klass();
amstin.models.grammar.Id obj52 = new amstin.models.grammar.Id();
amstin.models.grammar.Element obj14 = new amstin.models.grammar.Element();
amstin.models.grammar.IterStar obj40 = new amstin.models.grammar.IterStar();
amstin.models.grammar.Klass obj100 = new amstin.models.grammar.Klass();
amstin.models.grammar.Element obj33 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj6 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj3 = new amstin.models.grammar.Element();
amstin.models.grammar.Ref obj7 = new amstin.models.grammar.Ref();
amstin.models.grammar.Klass obj65 = new amstin.models.grammar.Klass();
amstin.models.grammar.Sym obj28 = new amstin.models.grammar.Sym();
amstin.models.grammar.Label obj102 = new amstin.models.grammar.Label();
amstin.models.grammar.Klass obj93 = new amstin.models.grammar.Klass();
amstin.models.grammar.Sym obj119 = new amstin.models.grammar.Sym();
amstin.models.grammar.Alt obj13 = new amstin.models.grammar.Alt();
amstin.models.grammar.Alt obj127 = new amstin.models.grammar.Alt();
amstin.models.grammar.Sym obj96 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj31 = new amstin.models.grammar.Element();
amstin.models.grammar.Rule obj42 = new amstin.models.grammar.Rule();
amstin.models.grammar.Alt obj92 = new amstin.models.grammar.Alt();
amstin.models.grammar.Element obj120 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj8 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj112 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj117 = new amstin.models.grammar.Element();
amstin.models.grammar.Klass obj84 = new amstin.models.grammar.Klass();
amstin.models.grammar.Klass obj89 = new amstin.models.grammar.Klass();
amstin.models.grammar.Lit obj130 = new amstin.models.grammar.Lit();
amstin.models.grammar.Alt obj72 = new amstin.models.grammar.Alt();
amstin.models.grammar.Label obj109 = new amstin.models.grammar.Label();
amstin.models.grammar.Rule obj29 = new amstin.models.grammar.Rule();
amstin.models.grammar.Lit obj18 = new amstin.models.grammar.Lit();
amstin.models.grammar.Alt obj68 = new amstin.models.grammar.Alt();
amstin.models.grammar.Lit obj71 = new amstin.models.grammar.Lit();
amstin.models.grammar.Label obj34 = new amstin.models.grammar.Label();
amstin.models.grammar.Lit obj116 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj66 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj20 = new amstin.models.grammar.Label();
amstin.models.grammar.Rule obj58 = new amstin.models.grammar.Rule();
amstin.models.grammar.Label obj95 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj111 = new amstin.models.grammar.Element();
amstin.models.grammar.Klass obj128 = new amstin.models.grammar.Klass();
amstin.models.grammar.Id obj80 = new amstin.models.grammar.Id();
amstin.models.grammar.Element obj36 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj140 = new amstin.models.grammar.Lit();
amstin.models.grammar.Opt obj27 = new amstin.models.grammar.Opt();
amstin.models.grammar.Lit obj4 = new amstin.models.grammar.Lit();
amstin.models.grammar.Label obj45 = new amstin.models.grammar.Label();
amstin.models.grammar.Alt obj113 = new amstin.models.grammar.Alt();
amstin.models.grammar.Sym obj22 = new amstin.models.grammar.Sym();
amstin.models.grammar.Sym obj41 = new amstin.models.grammar.Sym();
amstin.models.grammar.Klass obj60 = new amstin.models.grammar.Klass();
amstin.models.grammar.IterSep obj21 = new amstin.models.grammar.IterSep();
amstin.models.grammar.Element obj25 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj5 = new amstin.models.grammar.Element();
amstin.models.grammar.Rule obj12 = new amstin.models.grammar.Rule();
amstin.models.grammar.Element obj70 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj53 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj81 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj121 = new amstin.models.grammar.Label();
amstin.models.grammar.Sym obj11 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj90 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj139 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj135 = new amstin.models.grammar.Label();
amstin.models.grammar.Lit obj105 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj101 = new amstin.models.grammar.Element();
amstin.models.grammar.Sym obj110 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj125 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj137 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj64 = new amstin.models.grammar.Alt();
amstin.models.grammar.Lit obj82 = new amstin.models.grammar.Lit();
amstin.models.grammar.Lit obj67 = new amstin.models.grammar.Lit();
amstin.models.grammar.Grammar obj0 = new amstin.models.grammar.Grammar();
amstin.models.grammar.Element obj61 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj91 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj134 = new amstin.models.grammar.Element();
amstin.models.grammar.Rule obj48 = new amstin.models.grammar.Rule();
amstin.models.grammar.Element obj94 = new amstin.models.grammar.Element();
obj62.name = "rule";
obj39.name = "elements";
obj99.type = obj100;
obj99.elements = new ArrayList<amstin.models.grammar.Element>();
obj99.elements.add(obj101);
obj99.elements.add(obj104);
obj9.name = "rules";
obj63.ref = "Rule";
obj77.name = "Ref";
obj38.label = obj39;
obj38.symbol = obj40;
obj50.label = obj51;
obj50.symbol = obj52;
obj97.label = null;
obj97.symbol = obj98;
obj55.label = obj56;
obj55.symbol = obj57;
obj129.label = null;
obj129.symbol = obj130;
obj86.name = "value";
obj56.name = "symbol";
obj47.rule = obj48;
obj30.type = null;
obj30.elements = new ArrayList<amstin.models.grammar.Element>();
obj30.elements.add(obj31);
obj30.elements.add(obj33);
obj30.elements.add(obj36);
obj2.type = null;
obj2.elements = new ArrayList<amstin.models.grammar.Element>();
obj2.elements.add(obj3);
obj2.elements.add(obj5);
obj2.elements.add(obj8);
obj19.label = obj20;
obj19.symbol = obj21;
obj37.value = "]";
obj1.name = "Grammar";
obj1.alts = new ArrayList<amstin.models.grammar.Alt>();
obj1.alts.add(obj2);
obj17.label = null;
obj17.symbol = obj18;
obj76.type = obj77;
obj76.elements = new ArrayList<amstin.models.grammar.Element>();
obj76.elements.add(obj78);
obj76.elements.add(obj81);
obj32.value = "[";
obj88.type = obj89;
obj88.elements = new ArrayList<amstin.models.grammar.Element>();
obj88.elements.add(obj90);
obj103.rule = obj58;
obj106.type = obj107;
obj106.elements = new ArrayList<amstin.models.grammar.Element>();
obj106.elements.add(obj108);
obj106.elements.add(obj111);
obj59.type = obj60;
obj59.elements = new ArrayList<amstin.models.grammar.Element>();
obj59.elements.add(obj61);
obj75.value = "id";
obj79.name = "ref";
obj108.label = obj109;
obj108.symbol = obj110;
obj115.label = null;
obj115.symbol = obj116;
obj118.name = "arg";
obj83.type = obj84;
obj83.elements = new ArrayList<amstin.models.grammar.Element>();
obj83.elements.add(obj85);
obj132.name = "arg";
obj46.arg = obj47;
obj24.type = null;
obj24.elements = new ArrayList<amstin.models.grammar.Element>();
obj24.elements.add(obj25);
obj24.elements.add(obj38);
obj49.type = null;
obj49.elements = new ArrayList<amstin.models.grammar.Element>();
obj49.elements.add(obj50);
obj49.elements.add(obj53);
obj57.rule = obj58;
obj85.label = obj86;
obj85.symbol = obj87;
obj114.name = "IterSepStar";
obj123.label = null;
obj123.symbol = obj124;
obj98.value = "*";
obj15.name = "name";
obj26.name = "type";
obj44.label = obj45;
obj44.symbol = obj46;
obj54.value = ":";
obj138.value = "}";
obj10.arg = obj11;
obj78.label = obj79;
obj78.symbol = obj80;
obj131.label = obj132;
obj131.symbol = obj133;
obj73.name = "Id";
obj104.label = null;
obj104.symbol = obj105;
obj107.name = "Opt";
obj23.name = "Alt";
obj23.alts = new ArrayList<amstin.models.grammar.Alt>();
obj23.alts.add(obj24);
obj43.type = null;
obj43.elements = new ArrayList<amstin.models.grammar.Element>();
obj43.elements.add(obj44);
obj43.elements.add(obj55);
obj51.name = "name";
obj124.value = "}";
obj126.value = "*";
obj74.label = null;
obj74.symbol = obj75;
obj133.rule = obj58;
obj69.name = "Str";
obj14.label = obj15;
obj14.symbol = obj16;
obj40.arg = obj41;
obj100.name = "Iter";
obj33.label = obj34;
obj33.symbol = obj35;
obj6.name = "startSymbol";
obj3.label = null;
obj3.symbol = obj4;
obj7.ref = "Rule";
obj65.name = "Int";
obj28.rule = obj29;
obj102.name = "arg";
obj93.name = "IterStar";
obj119.rule = obj58;
obj13.type = null;
obj13.elements = new ArrayList<amstin.models.grammar.Element>();
obj13.elements.add(obj14);
obj13.elements.add(obj17);
obj13.elements.add(obj19);
obj127.type = obj128;
obj127.elements = new ArrayList<amstin.models.grammar.Element>();
obj127.elements.add(obj129);
obj127.elements.add(obj131);
obj127.elements.add(obj134);
obj127.elements.add(obj137);
obj127.elements.add(obj139);
obj96.rule = obj58;
obj31.label = null;
obj31.symbol = obj32;
obj42.name = "Element";
obj42.alts = new ArrayList<amstin.models.grammar.Alt>();
obj42.alts.add(obj43);
obj92.type = obj93;
obj92.elements = new ArrayList<amstin.models.grammar.Element>();
obj92.elements.add(obj94);
obj92.elements.add(obj97);
obj120.label = obj121;
obj120.symbol = obj122;
obj8.label = obj9;
obj8.symbol = obj10;
obj112.value = "?";
obj117.label = obj118;
obj117.symbol = obj119;
obj84.name = "Lit";
obj89.name = "Key";
obj130.value = "{";
obj72.type = obj73;
obj72.elements = new ArrayList<amstin.models.grammar.Element>();
obj72.elements.add(obj74);
obj109.name = "arg";
obj29.name = "Klass";
obj29.alts = new ArrayList<amstin.models.grammar.Alt>();
obj29.alts.add(obj30);
obj18.value = "::=";
obj68.type = obj69;
obj68.elements = new ArrayList<amstin.models.grammar.Element>();
obj68.elements.add(obj70);
obj71.value = "str";
obj34.name = "name";
obj116.value = "{";
obj66.label = null;
obj66.symbol = obj67;
obj20.name = "alts";
obj58.name = "Symbol";
obj58.alts = new ArrayList<amstin.models.grammar.Alt>();
obj58.alts.add(obj59);
obj58.alts.add(obj64);
obj58.alts.add(obj68);
obj58.alts.add(obj72);
obj58.alts.add(obj76);
obj58.alts.add(obj83);
obj58.alts.add(obj88);
obj58.alts.add(obj92);
obj58.alts.add(obj99);
obj58.alts.add(obj106);
obj58.alts.add(obj113);
obj58.alts.add(obj127);
obj95.name = "arg";
obj111.label = null;
obj111.symbol = obj112;
obj128.name = "IterSep";
obj36.label = null;
obj36.symbol = obj37;
obj140.value = "+";
obj27.arg = obj28;
obj4.value = "start";
obj45.name = "label";
obj113.type = obj114;
obj113.elements = new ArrayList<amstin.models.grammar.Element>();
obj113.elements.add(obj115);
obj113.elements.add(obj117);
obj113.elements.add(obj120);
obj113.elements.add(obj123);
obj113.elements.add(obj125);
obj22.rule = obj23;
obj41.rule = obj42;
obj60.name = "Sym";
obj21.arg = obj22;
obj21.sep = "|";
obj25.label = obj26;
obj25.symbol = obj27;
obj5.label = obj6;
obj5.symbol = obj7;
obj12.name = "Rule";
obj12.alts = new ArrayList<amstin.models.grammar.Alt>();
obj12.alts.add(obj13);
obj70.label = null;
obj70.symbol = obj71;
obj53.label = null;
obj53.symbol = obj54;
obj81.label = null;
obj81.symbol = obj82;
obj121.name = "sep";
obj11.rule = obj12;
obj90.label = null;
obj90.symbol = obj91;
obj139.label = null;
obj139.symbol = obj140;
obj135.name = "sep";
obj105.value = "+";
obj101.label = obj102;
obj101.symbol = obj103;
obj110.rule = obj58;
obj125.label = null;
obj125.symbol = obj126;
obj137.label = null;
obj137.symbol = obj138;
obj64.type = obj65;
obj64.elements = new ArrayList<amstin.models.grammar.Element>();
obj64.elements.add(obj66);
obj82.value = "^";
obj67.value = "int";
obj0.name = null;
obj0.startSymbol = obj1;
obj0.rules = new ArrayList<amstin.models.grammar.Rule>();
obj0.rules.add(obj1);
obj0.rules.add(obj12);
obj0.rules.add(obj23);
obj0.rules.add(obj29);
obj0.rules.add(obj42);
obj0.rules.add(obj48);
obj0.rules.add(obj58);
obj61.label = obj62;
obj61.symbol = obj63;
obj91.value = "key";
obj134.label = obj135;
obj134.symbol = obj136;
obj48.name = "Label";
obj48.alts = new ArrayList<amstin.models.grammar.Alt>();
obj48.alts.add(obj49);
obj94.label = obj95;
obj94.symbol = obj96;
instance = obj0;
}
}
