/* Generated at 2010/07/28 15:29:40; edit at your own risk. */

package amstin.models.grammar;

import java.util.ArrayList;

@SuppressWarnings("unchecked")
public class Boot {
public static final amstin.models.grammar.Grammar instance;
static {
amstin.models.grammar.Element obj61 = new amstin.models.grammar.Element();
amstin.models.grammar.Str obj126 = new amstin.models.grammar.Str();
amstin.models.grammar.Element obj138 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj96 = new amstin.models.grammar.Alt();
amstin.models.grammar.Ref obj7 = new amstin.models.grammar.Ref();
amstin.models.grammar.Element obj115 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj121 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj86 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj17 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj62 = new amstin.models.grammar.Label();
amstin.models.grammar.Lit obj75 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj127 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj128 = new amstin.models.grammar.Lit();
amstin.models.grammar.Rule obj58 = new amstin.models.grammar.Rule();
amstin.models.grammar.Lit obj109 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj135 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj54 = new amstin.models.grammar.Lit();
amstin.models.grammar.Opt obj46 = new amstin.models.grammar.Opt();
amstin.models.grammar.Sym obj28 = new amstin.models.grammar.Sym();
amstin.models.grammar.Id obj35 = new amstin.models.grammar.Id();
amstin.models.grammar.Label obj113 = new amstin.models.grammar.Label();
amstin.models.grammar.Str obj140 = new amstin.models.grammar.Str();
amstin.models.grammar.Grammar obj0 = new amstin.models.grammar.Grammar();
amstin.models.grammar.Element obj36 = new amstin.models.grammar.Element();
amstin.models.grammar.IterStar obj40 = new amstin.models.grammar.IterStar();
amstin.models.grammar.Sym obj100 = new amstin.models.grammar.Sym();
amstin.models.grammar.Alt obj103 = new amstin.models.grammar.Alt();
amstin.models.grammar.Sym obj57 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj31 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj44 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj74 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj108 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj124 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj136 = new amstin.models.grammar.Label();
amstin.models.grammar.Sym obj47 = new amstin.models.grammar.Sym();
amstin.models.grammar.Klass obj81 = new amstin.models.grammar.Klass();
amstin.models.grammar.Klass obj97 = new amstin.models.grammar.Klass();
amstin.models.grammar.Element obj19 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj38 = new amstin.models.grammar.Element();
amstin.models.grammar.IterSep obj21 = new amstin.models.grammar.IterSep();
amstin.models.grammar.Sym obj137 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj141 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj64 = new amstin.models.grammar.Alt();
amstin.models.grammar.Label obj9 = new amstin.models.grammar.Label();
amstin.models.grammar.Label obj15 = new amstin.models.grammar.Label();
amstin.models.grammar.Label obj99 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj105 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj71 = new amstin.models.grammar.Lit();
amstin.models.grammar.Sym obj123 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj129 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj59 = new amstin.models.grammar.Alt();
amstin.models.grammar.Sym obj22 = new amstin.models.grammar.Sym();
amstin.models.grammar.Label obj51 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj5 = new amstin.models.grammar.Element();
amstin.models.grammar.Sym obj41 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj53 = new amstin.models.grammar.Element();
amstin.models.grammar.Ref obj63 = new amstin.models.grammar.Ref();
amstin.models.grammar.Klass obj73 = new amstin.models.grammar.Klass();
amstin.models.grammar.Lit obj67 = new amstin.models.grammar.Lit();
amstin.models.grammar.Alt obj24 = new amstin.models.grammar.Alt();
amstin.models.grammar.Alt obj49 = new amstin.models.grammar.Alt();
amstin.models.grammar.Label obj39 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj14 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj68 = new amstin.models.grammar.Alt();
amstin.models.grammar.Element obj78 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj144 = new amstin.models.grammar.Lit();
amstin.models.grammar.Alt obj87 = new amstin.models.grammar.Alt();
amstin.models.grammar.Element obj143 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj94 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj6 = new amstin.models.grammar.Label();
amstin.models.grammar.Opt obj27 = new amstin.models.grammar.Opt();
amstin.models.grammar.Rule obj29 = new amstin.models.grammar.Rule();
amstin.models.grammar.Str obj91 = new amstin.models.grammar.Str();
amstin.models.grammar.Alt obj131 = new amstin.models.grammar.Alt();
amstin.models.grammar.Sym obj11 = new amstin.models.grammar.Sym();
amstin.models.grammar.Lit obj79 = new amstin.models.grammar.Lit();
amstin.models.grammar.Alt obj2 = new amstin.models.grammar.Alt();
amstin.models.grammar.Alt obj72 = new amstin.models.grammar.Alt();
amstin.models.grammar.Sym obj114 = new amstin.models.grammar.Sym();
amstin.models.grammar.Klass obj77 = new amstin.models.grammar.Klass();
amstin.models.grammar.Alt obj30 = new amstin.models.grammar.Alt();
amstin.models.grammar.Lit obj120 = new amstin.models.grammar.Lit();
amstin.models.grammar.Id obj84 = new amstin.models.grammar.Id();
amstin.models.grammar.Lit obj116 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj112 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj82 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj13 = new amstin.models.grammar.Alt();
amstin.models.grammar.Klass obj88 = new amstin.models.grammar.Klass();
amstin.models.grammar.Lit obj37 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj25 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj26 = new amstin.models.grammar.Label();
amstin.models.grammar.Key obj16 = new amstin.models.grammar.Key();
amstin.models.grammar.Label obj34 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj70 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj32 = new amstin.models.grammar.Lit();
amstin.models.grammar.Klass obj93 = new amstin.models.grammar.Klass();
amstin.models.grammar.Id obj52 = new amstin.models.grammar.Id();
amstin.models.grammar.Klass obj65 = new amstin.models.grammar.Klass();
amstin.models.grammar.Lit obj18 = new amstin.models.grammar.Lit();
amstin.models.grammar.Klass obj111 = new amstin.models.grammar.Klass();
amstin.models.grammar.Label obj56 = new amstin.models.grammar.Label();
amstin.models.grammar.Rule obj12 = new amstin.models.grammar.Rule();
amstin.models.grammar.Label obj122 = new amstin.models.grammar.Label();
amstin.models.grammar.Alt obj76 = new amstin.models.grammar.Alt();
amstin.models.grammar.Alt obj80 = new amstin.models.grammar.Alt();
amstin.models.grammar.IterStar obj10 = new amstin.models.grammar.IterStar();
amstin.models.grammar.Lit obj142 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj8 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj92 = new amstin.models.grammar.Alt();
amstin.models.grammar.Klass obj118 = new amstin.models.grammar.Klass();
amstin.models.grammar.Lit obj4 = new amstin.models.grammar.Lit();
amstin.models.grammar.Klass obj132 = new amstin.models.grammar.Klass();
amstin.models.grammar.Element obj133 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj101 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj55 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj110 = new amstin.models.grammar.Alt();
amstin.models.grammar.Element obj3 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj85 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj106 = new amstin.models.grammar.Label();
amstin.models.grammar.Label obj20 = new amstin.models.grammar.Label();
amstin.models.grammar.Rule obj42 = new amstin.models.grammar.Rule();
amstin.models.grammar.Label obj83 = new amstin.models.grammar.Label();
amstin.models.grammar.Klass obj69 = new amstin.models.grammar.Klass();
amstin.models.grammar.Alt obj117 = new amstin.models.grammar.Alt();
amstin.models.grammar.Element obj119 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj33 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj50 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj89 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj95 = new amstin.models.grammar.Lit();
amstin.models.grammar.Label obj139 = new amstin.models.grammar.Label();
amstin.models.grammar.Klass obj104 = new amstin.models.grammar.Klass();
amstin.models.grammar.Lit obj102 = new amstin.models.grammar.Lit();
amstin.models.grammar.Rule obj1 = new amstin.models.grammar.Rule();
amstin.models.grammar.Lit obj134 = new amstin.models.grammar.Lit();
amstin.models.grammar.Sym obj107 = new amstin.models.grammar.Sym();
amstin.models.grammar.Label obj125 = new amstin.models.grammar.Label();
amstin.models.grammar.Rule obj23 = new amstin.models.grammar.Rule();
amstin.models.grammar.Lit obj130 = new amstin.models.grammar.Lit();
amstin.models.grammar.Label obj90 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj66 = new amstin.models.grammar.Element();
amstin.models.grammar.Klass obj60 = new amstin.models.grammar.Klass();
amstin.models.grammar.Element obj98 = new amstin.models.grammar.Element();
amstin.models.grammar.Rule obj48 = new amstin.models.grammar.Rule();
amstin.models.grammar.Alt obj43 = new amstin.models.grammar.Alt();
amstin.models.grammar.Label obj45 = new amstin.models.grammar.Label();
obj61.label = obj62;
obj61.symbol = obj63;
obj138.label = obj139;
obj138.symbol = obj140;
obj96.type = obj97;
obj96.elements = new ArrayList<amstin.models.grammar.Element>();
obj96.elements.add(obj98);
obj96.elements.add(obj101);
obj7.ref = "Rule";
obj115.label = null;
obj115.symbol = obj116;
obj121.label = obj122;
obj121.symbol = obj123;
obj86.value = "^";
obj17.label = null;
obj17.symbol = obj18;
obj62.name = "rule";
obj75.value = "real";
obj127.label = null;
obj127.symbol = obj128;
obj128.value = "}";
obj58.name = "Symbol";
obj58.alts = new ArrayList<amstin.models.grammar.Alt>();
obj58.alts.add(obj59);
obj58.alts.add(obj64);
obj58.alts.add(obj68);
obj58.alts.add(obj72);
obj58.alts.add(obj76);
obj58.alts.add(obj80);
obj58.alts.add(obj87);
obj58.alts.add(obj92);
obj58.alts.add(obj96);
obj58.alts.add(obj103);
obj58.alts.add(obj110);
obj58.alts.add(obj117);
obj58.alts.add(obj131);
obj109.value = "+";
obj135.label = obj136;
obj135.symbol = obj137;
obj54.value = ":";
obj46.arg = obj47;
obj28.rule = obj29;
obj113.name = "arg";
obj0.name = null;
obj0.startSymbol = obj1;
obj0.rules = new ArrayList<amstin.models.grammar.Rule>();
obj0.rules.add(obj1);
obj0.rules.add(obj12);
obj0.rules.add(obj23);
obj0.rules.add(obj29);
obj0.rules.add(obj42);
obj0.rules.add(obj48);
obj0.rules.add(obj58);
obj36.label = null;
obj36.symbol = obj37;
obj40.arg = obj41;
obj100.rule = obj58;
obj103.type = obj104;
obj103.elements = new ArrayList<amstin.models.grammar.Element>();
obj103.elements.add(obj105);
obj103.elements.add(obj108);
obj57.rule = obj58;
obj31.label = null;
obj31.symbol = obj32;
obj44.label = obj45;
obj44.symbol = obj46;
obj74.label = null;
obj74.symbol = obj75;
obj108.label = null;
obj108.symbol = obj109;
obj124.label = obj125;
obj124.symbol = obj126;
obj136.name = "arg";
obj47.rule = obj48;
obj81.name = "Ref";
obj97.name = "IterStar";
obj19.label = obj20;
obj19.symbol = obj21;
obj38.label = obj39;
obj38.symbol = obj40;
obj21.arg = obj22;
obj21.sep = "|";
obj137.rule = obj58;
obj141.label = null;
obj141.symbol = obj142;
obj64.type = obj65;
obj64.elements = new ArrayList<amstin.models.grammar.Element>();
obj64.elements.add(obj66);
obj9.name = "rules";
obj15.name = "name";
obj99.name = "arg";
obj105.label = obj106;
obj105.symbol = obj107;
obj71.value = "str";
obj123.rule = obj58;
obj129.label = null;
obj129.symbol = obj130;
obj59.type = obj60;
obj59.elements = new ArrayList<amstin.models.grammar.Element>();
obj59.elements.add(obj61);
obj22.rule = obj23;
obj51.name = "name";
obj5.label = obj6;
obj5.symbol = obj7;
obj41.rule = obj42;
obj53.label = null;
obj53.symbol = obj54;
obj63.ref = "Rule";
obj73.name = "Real";
obj67.value = "int";
obj24.type = null;
obj24.elements = new ArrayList<amstin.models.grammar.Element>();
obj24.elements.add(obj25);
obj24.elements.add(obj38);
obj49.type = null;
obj49.elements = new ArrayList<amstin.models.grammar.Element>();
obj49.elements.add(obj50);
obj49.elements.add(obj53);
obj39.name = "elements";
obj14.label = obj15;
obj14.symbol = obj16;
obj68.type = obj69;
obj68.elements = new ArrayList<amstin.models.grammar.Element>();
obj68.elements.add(obj70);
obj78.label = null;
obj78.symbol = obj79;
obj144.value = "+";
obj87.type = obj88;
obj87.elements = new ArrayList<amstin.models.grammar.Element>();
obj87.elements.add(obj89);
obj143.label = null;
obj143.symbol = obj144;
obj94.label = null;
obj94.symbol = obj95;
obj6.name = "startSymbol";
obj27.arg = obj28;
obj29.name = "Klass";
obj29.alts = new ArrayList<amstin.models.grammar.Alt>();
obj29.alts.add(obj30);
obj131.type = obj132;
obj131.elements = new ArrayList<amstin.models.grammar.Element>();
obj131.elements.add(obj133);
obj131.elements.add(obj135);
obj131.elements.add(obj138);
obj131.elements.add(obj141);
obj131.elements.add(obj143);
obj11.rule = obj12;
obj79.value = "id";
obj2.type = null;
obj2.elements = new ArrayList<amstin.models.grammar.Element>();
obj2.elements.add(obj3);
obj2.elements.add(obj5);
obj2.elements.add(obj8);
obj72.type = obj73;
obj72.elements = new ArrayList<amstin.models.grammar.Element>();
obj72.elements.add(obj74);
obj114.rule = obj58;
obj77.name = "Id";
obj30.type = null;
obj30.elements = new ArrayList<amstin.models.grammar.Element>();
obj30.elements.add(obj31);
obj30.elements.add(obj33);
obj30.elements.add(obj36);
obj120.value = "{";
obj116.value = "?";
obj112.label = obj113;
obj112.symbol = obj114;
obj82.label = obj83;
obj82.symbol = obj84;
obj13.type = null;
obj13.elements = new ArrayList<amstin.models.grammar.Element>();
obj13.elements.add(obj14);
obj13.elements.add(obj17);
obj13.elements.add(obj19);
obj88.name = "Lit";
obj37.value = "]";
obj25.label = obj26;
obj25.symbol = obj27;
obj26.name = "type";
obj34.name = "name";
obj70.label = null;
obj70.symbol = obj71;
obj32.value = "[";
obj93.name = "Key";
obj65.name = "Int";
obj18.value = "::=";
obj111.name = "Opt";
obj56.name = "symbol";
obj12.name = "Rule";
obj12.alts = new ArrayList<amstin.models.grammar.Alt>();
obj12.alts.add(obj13);
obj122.name = "arg";
obj76.type = obj77;
obj76.elements = new ArrayList<amstin.models.grammar.Element>();
obj76.elements.add(obj78);
obj80.type = obj81;
obj80.elements = new ArrayList<amstin.models.grammar.Element>();
obj80.elements.add(obj82);
obj80.elements.add(obj85);
obj10.arg = obj11;
obj142.value = "}";
obj8.label = obj9;
obj8.symbol = obj10;
obj92.type = obj93;
obj92.elements = new ArrayList<amstin.models.grammar.Element>();
obj92.elements.add(obj94);
obj118.name = "IterSepStar";
obj4.value = "start";
obj132.name = "IterSep";
obj133.label = null;
obj133.symbol = obj134;
obj101.label = null;
obj101.symbol = obj102;
obj55.label = obj56;
obj55.symbol = obj57;
obj110.type = obj111;
obj110.elements = new ArrayList<amstin.models.grammar.Element>();
obj110.elements.add(obj112);
obj110.elements.add(obj115);
obj3.label = null;
obj3.symbol = obj4;
obj85.label = null;
obj85.symbol = obj86;
obj106.name = "arg";
obj20.name = "alts";
obj42.name = "Element";
obj42.alts = new ArrayList<amstin.models.grammar.Alt>();
obj42.alts.add(obj43);
obj83.name = "ref";
obj69.name = "Str";
obj117.type = obj118;
obj117.elements = new ArrayList<amstin.models.grammar.Element>();
obj117.elements.add(obj119);
obj117.elements.add(obj121);
obj117.elements.add(obj124);
obj117.elements.add(obj127);
obj117.elements.add(obj129);
obj119.label = null;
obj119.symbol = obj120;
obj33.label = obj34;
obj33.symbol = obj35;
obj50.label = obj51;
obj50.symbol = obj52;
obj89.label = obj90;
obj89.symbol = obj91;
obj95.value = "key";
obj139.name = "sep";
obj104.name = "Iter";
obj102.value = "*";
obj1.name = "Grammar";
obj1.alts = new ArrayList<amstin.models.grammar.Alt>();
obj1.alts.add(obj2);
obj134.value = "{";
obj107.rule = obj58;
obj125.name = "sep";
obj23.name = "Alt";
obj23.alts = new ArrayList<amstin.models.grammar.Alt>();
obj23.alts.add(obj24);
obj130.value = "*";
obj90.name = "value";
obj66.label = null;
obj66.symbol = obj67;
obj60.name = "Sym";
obj98.label = obj99;
obj98.symbol = obj100;
obj48.name = "Label";
obj48.alts = new ArrayList<amstin.models.grammar.Alt>();
obj48.alts.add(obj49);
obj43.type = null;
obj43.elements = new ArrayList<amstin.models.grammar.Element>();
obj43.elements.add(obj44);
obj43.elements.add(obj55);
obj45.name = "label";
instance = obj0;
}
}
