/* Generated at 2010/08/05 14:41:59; edit at your own risk. */

package amstin.models.grammar;

import java.util.ArrayList;

@SuppressWarnings("unchecked")
public class Boot {
public static final amstin.models.grammar.Grammar instance;
static {
amstin.models.grammar.Str obj130 = new amstin.models.grammar.Str();
amstin.models.grammar.Element obj50 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj4 = new amstin.models.grammar.Lit();
amstin.models.grammar.Rule obj1 = new amstin.models.grammar.Rule();
amstin.models.grammar.Element obj112 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj44 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj87 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj131 = new amstin.models.grammar.Element();
amstin.models.grammar.Rule obj12 = new amstin.models.grammar.Rule();
amstin.models.grammar.Sym obj127 = new amstin.models.grammar.Sym();
amstin.models.grammar.Alt obj135 = new amstin.models.grammar.Alt();
amstin.models.grammar.Label obj126 = new amstin.models.grammar.Label();
amstin.models.grammar.Alt obj30 = new amstin.models.grammar.Alt();
amstin.models.grammar.Sym obj22 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj14 = new amstin.models.grammar.Element();
amstin.models.grammar.Rule obj42 = new amstin.models.grammar.Rule();
amstin.models.grammar.Ref obj63 = new amstin.models.grammar.Ref();
amstin.models.grammar.Alt obj64 = new amstin.models.grammar.Alt();
amstin.models.grammar.Alt obj72 = new amstin.models.grammar.Alt();
amstin.models.grammar.Lit obj132 = new amstin.models.grammar.Lit();
amstin.models.grammar.Lit obj99 = new amstin.models.grammar.Lit();
amstin.models.grammar.Alt obj91 = new amstin.models.grammar.Alt();
amstin.models.grammar.Sym obj141 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj93 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj18 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj66 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj56 = new amstin.models.grammar.Label();
amstin.models.grammar.Alt obj68 = new amstin.models.grammar.Alt();
amstin.models.grammar.Klass obj73 = new amstin.models.grammar.Klass();
amstin.models.grammar.Lit obj113 = new amstin.models.grammar.Lit();
amstin.models.grammar.Sym obj28 = new amstin.models.grammar.Sym();
amstin.models.grammar.Lit obj37 = new amstin.models.grammar.Lit();
amstin.models.grammar.Alt obj43 = new amstin.models.grammar.Alt();
amstin.models.grammar.Id obj88 = new amstin.models.grammar.Id();
amstin.models.grammar.Label obj117 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj53 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj71 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj145 = new amstin.models.grammar.Element();
amstin.models.grammar.Sym obj118 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj133 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj49 = new amstin.models.grammar.Alt();
amstin.models.grammar.Label obj143 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj8 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj55 = new amstin.models.grammar.Element();
amstin.models.grammar.Opt obj46 = new amstin.models.grammar.Opt();
amstin.models.grammar.Element obj31 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj2 = new amstin.models.grammar.Alt();
amstin.models.grammar.Rule obj29 = new amstin.models.grammar.Rule();
amstin.models.grammar.Element obj36 = new amstin.models.grammar.Element();
amstin.models.grammar.Klass obj92 = new amstin.models.grammar.Klass();
amstin.models.grammar.Sym obj111 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj116 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj138 = new amstin.models.grammar.Lit();
amstin.models.grammar.Label obj129 = new amstin.models.grammar.Label();
amstin.models.grammar.Label obj15 = new amstin.models.grammar.Label();
amstin.models.grammar.Lit obj120 = new amstin.models.grammar.Lit();
amstin.models.grammar.Sym obj11 = new amstin.models.grammar.Sym();
amstin.models.grammar.Sym obj41 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj139 = new amstin.models.grammar.Element();
amstin.models.grammar.Klass obj77 = new amstin.models.grammar.Klass();
amstin.models.grammar.Element obj25 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj38 = new amstin.models.grammar.Element();
amstin.models.grammar.Sym obj57 = new amstin.models.grammar.Sym();
amstin.models.grammar.Klass obj81 = new amstin.models.grammar.Klass();
amstin.models.grammar.Klass obj60 = new amstin.models.grammar.Klass();
amstin.models.grammar.Key obj16 = new amstin.models.grammar.Key();
amstin.models.grammar.Lit obj79 = new amstin.models.grammar.Lit();
amstin.models.grammar.Alt obj84 = new amstin.models.grammar.Alt();
amstin.models.grammar.Element obj109 = new amstin.models.grammar.Element();
amstin.models.grammar.Str obj144 = new amstin.models.grammar.Str();
amstin.models.grammar.Klass obj97 = new amstin.models.grammar.Klass();
amstin.models.grammar.Element obj142 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj5 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj78 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj98 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj45 = new amstin.models.grammar.Label();
amstin.models.grammar.Alt obj80 = new amstin.models.grammar.Alt();
amstin.models.grammar.Element obj119 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj70 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj128 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj100 = new amstin.models.grammar.Alt();
amstin.models.grammar.Alt obj76 = new amstin.models.grammar.Alt();
amstin.models.grammar.Lit obj134 = new amstin.models.grammar.Lit();
amstin.models.grammar.Id obj35 = new amstin.models.grammar.Id();
amstin.models.grammar.Label obj140 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj17 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj83 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj125 = new amstin.models.grammar.Element();
amstin.models.grammar.Klass obj136 = new amstin.models.grammar.Klass();
amstin.models.grammar.Lit obj90 = new amstin.models.grammar.Lit();
amstin.models.grammar.Alt obj59 = new amstin.models.grammar.Alt();
amstin.models.grammar.Lit obj106 = new amstin.models.grammar.Lit();
amstin.models.grammar.Label obj34 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj74 = new amstin.models.grammar.Element();
amstin.models.grammar.Alt obj114 = new amstin.models.grammar.Alt();
amstin.models.grammar.Str obj95 = new amstin.models.grammar.Str();
amstin.models.grammar.Element obj102 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj33 = new amstin.models.grammar.Element();
amstin.models.grammar.IterSep obj21 = new amstin.models.grammar.IterSep();
amstin.models.grammar.Alt obj107 = new amstin.models.grammar.Alt();
amstin.models.grammar.Lit obj32 = new amstin.models.grammar.Lit();
amstin.models.grammar.Alt obj121 = new amstin.models.grammar.Alt();
amstin.models.grammar.Rule obj48 = new amstin.models.grammar.Rule();
amstin.models.grammar.Label obj6 = new amstin.models.grammar.Label();
amstin.models.grammar.Label obj94 = new amstin.models.grammar.Label();
amstin.models.grammar.Klass obj101 = new amstin.models.grammar.Klass();
amstin.models.grammar.Alt obj13 = new amstin.models.grammar.Alt();
amstin.models.grammar.Ref obj7 = new amstin.models.grammar.Ref();
amstin.models.grammar.Klass obj65 = new amstin.models.grammar.Klass();
amstin.models.grammar.Label obj39 = new amstin.models.grammar.Label();
amstin.models.grammar.Rule obj58 = new amstin.models.grammar.Rule();
amstin.models.grammar.Lit obj54 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj105 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj82 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj75 = new amstin.models.grammar.Lit();
amstin.models.grammar.Klass obj122 = new amstin.models.grammar.Klass();
amstin.models.grammar.Element obj137 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj9 = new amstin.models.grammar.Label();
amstin.models.grammar.Alt obj24 = new amstin.models.grammar.Alt();
amstin.models.grammar.Label obj110 = new amstin.models.grammar.Label();
amstin.models.grammar.Lit obj146 = new amstin.models.grammar.Lit();
amstin.models.grammar.Lit obj148 = new amstin.models.grammar.Lit();
amstin.models.grammar.Grammar obj0 = new amstin.models.grammar.Grammar();
amstin.models.grammar.Element obj3 = new amstin.models.grammar.Element();
amstin.models.grammar.IterStar obj10 = new amstin.models.grammar.IterStar();
amstin.models.grammar.Klass obj69 = new amstin.models.grammar.Klass();
amstin.models.grammar.Label obj62 = new amstin.models.grammar.Label();
amstin.models.grammar.Element obj89 = new amstin.models.grammar.Element();
amstin.models.grammar.Klass obj115 = new amstin.models.grammar.Klass();
amstin.models.grammar.Klass obj85 = new amstin.models.grammar.Klass();
amstin.models.grammar.Sym obj104 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj19 = new amstin.models.grammar.Element();
amstin.models.grammar.Element obj123 = new amstin.models.grammar.Element();
amstin.models.grammar.IterStar obj40 = new amstin.models.grammar.IterStar();
amstin.models.grammar.Id obj52 = new amstin.models.grammar.Id();
amstin.models.grammar.Rule obj23 = new amstin.models.grammar.Rule();
amstin.models.grammar.Element obj86 = new amstin.models.grammar.Element();
amstin.models.grammar.Lit obj124 = new amstin.models.grammar.Lit();
amstin.models.grammar.Element obj61 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj26 = new amstin.models.grammar.Label();
amstin.models.grammar.Alt obj96 = new amstin.models.grammar.Alt();
amstin.models.grammar.Lit obj67 = new amstin.models.grammar.Lit();
amstin.models.grammar.Klass obj108 = new amstin.models.grammar.Klass();
amstin.models.grammar.Sym obj47 = new amstin.models.grammar.Sym();
amstin.models.grammar.Element obj147 = new amstin.models.grammar.Element();
amstin.models.grammar.Label obj51 = new amstin.models.grammar.Label();
amstin.models.grammar.Label obj103 = new amstin.models.grammar.Label();
amstin.models.grammar.Opt obj27 = new amstin.models.grammar.Opt();
amstin.models.grammar.Label obj20 = new amstin.models.grammar.Label();
obj50.label = obj51;
obj50.symbol = obj52;
obj4.value = "start";
obj1.name = "Grammar";
obj1.alts = new ArrayList<amstin.models.grammar.Alt>();
obj1.alts.add(obj2);
obj112.label = null;
obj112.symbol = obj113;
obj44.label = obj45;
obj44.symbol = obj46;
obj87.name = "ref";
obj131.label = null;
obj131.symbol = obj132;
obj12.name = "Rule";
obj12.alts = new ArrayList<amstin.models.grammar.Alt>();
obj12.alts.add(obj13);
obj127.rule = obj58;
obj135.type = obj136;
obj135.elements = new ArrayList<amstin.models.grammar.Element>();
obj135.elements.add(obj137);
obj135.elements.add(obj139);
obj135.elements.add(obj142);
obj135.elements.add(obj145);
obj135.elements.add(obj147);
obj126.name = "arg";
obj30.type = null;
obj30.elements = new ArrayList<amstin.models.grammar.Element>();
obj30.elements.add(obj31);
obj30.elements.add(obj33);
obj30.elements.add(obj36);
obj22.rule = obj23;
obj14.label = obj15;
obj14.symbol = obj16;
obj42.name = "Element";
obj42.alts = new ArrayList<amstin.models.grammar.Alt>();
obj42.alts.add(obj43);
obj63.ref = "Rule";
obj64.type = obj65;
obj64.elements = new ArrayList<amstin.models.grammar.Element>();
obj64.elements.add(obj66);
obj72.type = obj73;
obj72.elements = new ArrayList<amstin.models.grammar.Element>();
obj72.elements.add(obj74);
obj132.value = "}";
obj99.value = "key";
obj91.type = obj92;
obj91.elements = new ArrayList<amstin.models.grammar.Element>();
obj91.elements.add(obj93);
obj141.rule = obj58;
obj93.label = obj94;
obj93.symbol = obj95;
obj18.value = "::=";
obj66.label = null;
obj66.symbol = obj67;
obj56.name = "symbol";
obj68.type = obj69;
obj68.elements = new ArrayList<amstin.models.grammar.Element>();
obj68.elements.add(obj70);
obj73.name = "Real";
obj113.value = "+";
obj28.rule = obj29;
obj37.value = "]";
obj43.type = null;
obj43.elements = new ArrayList<amstin.models.grammar.Element>();
obj43.elements.add(obj44);
obj43.elements.add(obj55);
obj117.name = "arg";
obj53.label = null;
obj53.symbol = obj54;
obj71.value = "str";
obj145.label = null;
obj145.symbol = obj146;
obj118.rule = obj58;
obj133.label = null;
obj133.symbol = obj134;
obj49.type = null;
obj49.elements = new ArrayList<amstin.models.grammar.Element>();
obj49.elements.add(obj50);
obj49.elements.add(obj53);
obj143.name = "sep";
obj8.label = obj9;
obj8.symbol = obj10;
obj55.label = obj56;
obj55.symbol = obj57;
obj46.arg = obj47;
obj31.label = null;
obj31.symbol = obj32;
obj2.type = null;
obj2.elements = new ArrayList<amstin.models.grammar.Element>();
obj2.elements.add(obj3);
obj2.elements.add(obj5);
obj2.elements.add(obj8);
obj29.name = "Klass";
obj29.alts = new ArrayList<amstin.models.grammar.Alt>();
obj29.alts.add(obj30);
obj36.label = null;
obj36.symbol = obj37;
obj92.name = "Lit";
obj111.rule = obj58;
obj116.label = obj117;
obj116.symbol = obj118;
obj138.value = "{";
obj129.name = "sep";
obj15.name = "name";
obj120.value = "?";
obj11.rule = obj12;
obj41.rule = obj42;
obj139.label = obj140;
obj139.symbol = obj141;
obj77.name = "Bool";
obj25.label = obj26;
obj25.symbol = obj27;
obj38.label = obj39;
obj38.symbol = obj40;
obj57.rule = obj58;
obj81.name = "Id";
obj60.name = "Sym";
obj79.value = "bool";
obj84.type = obj85;
obj84.elements = new ArrayList<amstin.models.grammar.Element>();
obj84.elements.add(obj86);
obj84.elements.add(obj89);
obj109.label = obj110;
obj109.symbol = obj111;
obj97.name = "Key";
obj142.label = obj143;
obj142.symbol = obj144;
obj5.label = obj6;
obj5.symbol = obj7;
obj78.label = null;
obj78.symbol = obj79;
obj98.label = null;
obj98.symbol = obj99;
obj45.name = "label";
obj80.type = obj81;
obj80.elements = new ArrayList<amstin.models.grammar.Element>();
obj80.elements.add(obj82);
obj119.label = null;
obj119.symbol = obj120;
obj70.label = null;
obj70.symbol = obj71;
obj128.label = obj129;
obj128.symbol = obj130;
obj100.type = obj101;
obj100.elements = new ArrayList<amstin.models.grammar.Element>();
obj100.elements.add(obj102);
obj100.elements.add(obj105);
obj76.type = obj77;
obj76.elements = new ArrayList<amstin.models.grammar.Element>();
obj76.elements.add(obj78);
obj134.value = "*";
obj140.name = "arg";
obj17.label = null;
obj17.symbol = obj18;
obj83.value = "id";
obj125.label = obj126;
obj125.symbol = obj127;
obj136.name = "IterSep";
obj90.value = "^";
obj59.type = obj60;
obj59.elements = new ArrayList<amstin.models.grammar.Element>();
obj59.elements.add(obj61);
obj106.value = "*";
obj34.name = "name";
obj74.label = null;
obj74.symbol = obj75;
obj114.type = obj115;
obj114.elements = new ArrayList<amstin.models.grammar.Element>();
obj114.elements.add(obj116);
obj114.elements.add(obj119);
obj102.label = obj103;
obj102.symbol = obj104;
obj33.label = obj34;
obj33.symbol = obj35;
obj21.arg = obj22;
obj21.sep = "|";
obj107.type = obj108;
obj107.elements = new ArrayList<amstin.models.grammar.Element>();
obj107.elements.add(obj109);
obj107.elements.add(obj112);
obj32.value = "[";
obj121.type = obj122;
obj121.elements = new ArrayList<amstin.models.grammar.Element>();
obj121.elements.add(obj123);
obj121.elements.add(obj125);
obj121.elements.add(obj128);
obj121.elements.add(obj131);
obj121.elements.add(obj133);
obj48.name = "Label";
obj48.alts = new ArrayList<amstin.models.grammar.Alt>();
obj48.alts.add(obj49);
obj6.name = "startSymbol";
obj94.name = "value";
obj101.name = "IterStar";
obj13.type = null;
obj13.elements = new ArrayList<amstin.models.grammar.Element>();
obj13.elements.add(obj14);
obj13.elements.add(obj17);
obj13.elements.add(obj19);
obj7.ref = "Rule";
obj65.name = "Int";
obj39.name = "elements";
obj58.name = "Symbol";
obj58.alts = new ArrayList<amstin.models.grammar.Alt>();
obj58.alts.add(obj59);
obj58.alts.add(obj64);
obj58.alts.add(obj68);
obj58.alts.add(obj72);
obj58.alts.add(obj76);
obj58.alts.add(obj80);
obj58.alts.add(obj84);
obj58.alts.add(obj91);
obj58.alts.add(obj96);
obj58.alts.add(obj100);
obj58.alts.add(obj107);
obj58.alts.add(obj114);
obj58.alts.add(obj121);
obj58.alts.add(obj135);
obj54.value = ":";
obj105.label = null;
obj105.symbol = obj106;
obj82.label = null;
obj82.symbol = obj83;
obj75.value = "real";
obj122.name = "IterSepStar";
obj137.label = null;
obj137.symbol = obj138;
obj9.name = "rules";
obj24.type = null;
obj24.elements = new ArrayList<amstin.models.grammar.Element>();
obj24.elements.add(obj25);
obj24.elements.add(obj38);
obj110.name = "arg";
obj146.value = "}";
obj148.value = "+";
obj0.startSymbol = obj1;
obj0.rules = new ArrayList<amstin.models.grammar.Rule>();
obj0.rules.add(obj1);
obj0.rules.add(obj12);
obj0.rules.add(obj23);
obj0.rules.add(obj29);
obj0.rules.add(obj42);
obj0.rules.add(obj48);
obj0.rules.add(obj58);
obj3.label = null;
obj3.symbol = obj4;
obj10.arg = obj11;
obj69.name = "Str";
obj62.name = "rule";
obj89.label = null;
obj89.symbol = obj90;
obj115.name = "Opt";
obj85.name = "Ref";
obj104.rule = obj58;
obj19.label = obj20;
obj19.symbol = obj21;
obj123.label = null;
obj123.symbol = obj124;
obj40.arg = obj41;
obj23.name = "Alt";
obj23.alts = new ArrayList<amstin.models.grammar.Alt>();
obj23.alts.add(obj24);
obj86.label = obj87;
obj86.symbol = obj88;
obj124.value = "{";
obj61.label = obj62;
obj61.symbol = obj63;
obj26.name = "type";
obj96.type = obj97;
obj96.elements = new ArrayList<amstin.models.grammar.Element>();
obj96.elements.add(obj98);
obj67.value = "int";
obj108.name = "Iter";
obj47.rule = obj48;
obj147.label = null;
obj147.symbol = obj148;
obj51.name = "name";
obj103.name = "arg";
obj27.arg = obj28;
obj20.name = "alts";
instance = obj0;
}
}
